---
codecov:
  branch: main
  require_ci_to_pass: true

coverage:
  threshold: 5%
  precision: 2
  round: down
  range: "70..100"
  status:
    patch: off

parsers:
  gcov:
    branch_detection:
      conditional: yes
      loop: yes
      method: no
      macro: no

comment:
  layout: "reach,diff,flags,files,footer"
  behavior: default
  require_changes: false
