= java.util extensions

image:https://github.com/mihxil/utils/actions/workflows/maven.yml/badge.svg?[Build Status,link=https://github.com/mihxil/utils/actions/workflows/maven.yml]
image:https://img.shields.io/maven-central/v/org.meeuw.util/mihxil-functional.svg?label=Maven%20Central[Maven Central,link=https://central.sonatype.com/artifact/org.meeuw.util/mihxil-functional/overview]
image:https://codecov.io/gh/mihxil/utils/branch/main/graph/badge.svg[codecov,link=https://codecov.io/gh/mihxil/utils]
image:https://javadoc.io/badge/org.meeuw.util/mihxil-functional.svg?color=blue[javadoc,link=https://javadoc.io/doc/org.meeuw.util/mihxil-functional]
//image:https://img.shields.io/nexus/s/https/oss.sonatype.org/org.meeuw.util/mihxil-functional.svg[snapshots,link=https://oss.sonatype.org/content/repositories/snapshots/org/meeuw/util/]



== Functional extensions

Classes related to `java.util.Function` and extensions like `Predicate`, `Consumer` and `Supplier`.

* link:mihxil-functional/src/main/java/org/meeuw/functional/TriFunction.java[`TriFunction`], link:mihxil-functional/src/main/java/org/meeuw/functional/QuadriFunction.java[`QuadriFunction`]
* link:mihxil-functional/src/main/java/org/meeuw/functional/TriConsumer.java[`TriConsumer`]
* link:mihxil-functional/src/main/java/org/meeuw/functional/TriPredicate.java[`TriPredicate`]
* Morphing methods like

** `TriFunction#ignoreArg[1-4](...)` morphs a `TriFunction` to a `QuadriFunction`
** `TriFunction#withArg[1-3](...)` morphs a `TriFunction` to a `BiFunction`.

*  Utilities for that in

** link:mihxil-functional/src/main/java/org/meeuw/functional/Functions.java[`Functions`]
+

+
** link:mihxil-functional/src/main/java/org/meeuw/functional/Consumers.java[`Consumers`]
** link:mihxil-functional/src/main/java/org/meeuw/functional/Predicates.java[`Predicates`],
** link:mihxil-functional/src/main/java/org/meeuw/functional/Suppliers.java[`Suppliers`]
+
Things like `memoize` (to memoize the value of a supplier), `closeable` (to make a Supplier `AutoCloseable`) and  `ignoreArg` (to morph a `Supplier` to a `Function` that ignores the argument) are provided.
+
* Consistent `equals` and `hashCode`, for the utility functions that produce functional implementations. E.g. the  above mentioned `ignoreArg*` and `withArg*` are not simply implemented with lambda's, but also with equals and hashcode based on the source functional class implementation.

== Release history


|===
|Version |date |remarks

|1.12
| 2025-06-26
|
A.o, introduction of 'CloseableSupplier' and 'UnwrappableSupplier' interfaces,


|1.11
| 2024-05-11
|

| 1.10
| 2023-12
|

| 1.0
| 2020-11-30
|
|===

