= java.util extensions


image:https://travis-ci.com/mihxil/utils.svg?[Build Status,link=https://travis-ci.com/mihxil/utils]
image:https://img.shields.io/maven-central/v/org.meeuw.util/mihxil-functional.svg?label=Maven%20Central[Maven Central,link=https://search.maven.org/search?q=g:%22org.meeuw.util%22]
image:https://codecov.io/gh/mihxil/utils/branch/master/graph/badge.svg[codecov,link=https://codecov.io/gh/mihxil/utils]


== Functional extensions

Classes related to `java.util.Function` and extensions like `Predicate`, `Consumer` and `Supplier`.

- link:mihxil-functional/src/main/java/org/meeuw/functional/TriFunction.java[`TriFunction`], `QuadriFunction`
- `TriConsumer`
- `TriPredicate`
- Consistent `equals` and `hashCode`
- Morphing methods like
  - `TriFunction#ignoreArg[1-4](..)` morphs a `TriFunction` to a `QuadriFunction`
  - `TriFunction#withArg[1-3](..)` morhps a `TriFunction` to a `BiFunction`

- Utilities for that in link:mihxil-functional/src/main/java/org/meeuw/functional/Functions.java[`Functions`], link:mihxil-functional/src/main/java/org/meeuw/functional/Consumers.java[`Consumers`], link:mihxil-functional/src/main/java/org/meeuw/functional/Predicates.java[`Predicates`]
