= java.util extensions

image:https://github.com/mihxil/utils/actions/workflows/maven.yml/badge.svg?[Build Status,link=https://github.com/mihxil/utils/actions/workflows/maven.yml]
image:https://img.shields.io/maven-central/v/org.meeuw.util/mihxil-functional.svg?label=Maven%20Central[Maven Central,link=https://search.maven.org/search?q=g:%22org.meeuw.util%22]
image:https://codecov.io/gh/mihxil/utils/branch/main/graph/badge.svg[codecov,link=https://codecov.io/gh/mihxil/utils]
image:https://www.javadoc.io/badge/org.meeuw.util/mihxil-functional.svg?color=blue[javadoc,link=https://www.javadoc.io/doc/org.meeuw.util/mihxil-functional]



== Functional extensions

Classes related to `java.util.Function` and extensions like `Predicate`, `Consumer` and `Supplier`.

* link:mihxil-functional/src/main/java/org/meeuw/functional/TriFunction.java[`TriFunction`], link:mihxil-functional/src/main/java/org/meeuw/functional/QuadriFunction.java[`QuadriFunction`]
* link:mihxil-functional/src/main/java/org/meeuw/functional/TriConsumer.java[`TriConsumer`]
* link:mihxil-functional/src/main/java/org/meeuw/functional/TriPredicate.java[`TriPredicate`]
* Morphing methods like

** `TriFunction#ignoreArg[1-4](...)` morphs a `TriFunction` to a `QuadriFunction`
** `TriFunction#withArg[1-3](...)` morphs a `TriFunction` to a `BiFunction`.

*  Utilities for that in link:mihxil-functional/src/main/java/org/meeuw/functional/Functions.java[`Functions`], link:mihxil-functional/src/main/java/org/meeuw/functional/Consumers.java[`Consumers`], link:mihxil-functional/src/main/java/org/meeuw/functional/Predicates.java[`Predicates`]
* Consistent `equals` and `hashCode`, for the utility functions that produce functional implementations. E.g. the  above mentioned `ignoreArg*` and `withArg*` are not simply implemented with lambda's, but also with equals and hashcode based on the source functional class implementation.
