---
name: build
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-latest, windows-latest, macos-latest ]
        java: [ 8 ]
        # also check (once) on latest
        include:
          - os: ubuntu-latest
            java: 24
    env:
      MAVEN_ARGS: '--no-transfer-progress'
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: ${{ matrix.java }}
          distribution: 'temurin'
          cache: "maven"
          server-id: central
          server-username: CENTRAL_USERNAME
          server-password: CENTRAL_PASSWORD
          gpg-private-key: ${{ secrets.GPG_SECRET_KEY }}
      - name: Set Maven Target
        run: |
          if [[ "${{ matrix.os }}" == "ubuntu-latest" && "${{ matrix.java }}" == "8" ]]; then
            echo "MAVEN_TARGET=deploy" >> $GITHUB_ENV
          else
            echo "MAVEN_TARGET=package" >> $GITHUB_ENV
          fi
      - name: Build with Maven
        run: |
          mvn -B -Pdeploy -fae ${{ env.MAVEN_TARGET }}
        env:
          CENTRAL_USERNAME: ${{ secrets.CENTRAL_USERNAME }}
          CENTRAL_PASSWORD: ${{ secrets.CENTRAL_PASSWORD }}
          MAVEN_GPG_PASSPHRASE: ${{ secrets.GPG_SECRET_KEY_PASSPHRASE }}
      - uses: codecov/codecov-action@v4
        if: ${{ github.event_name == 'push'  && ! cancelled() }}
        with:
          token: ${{ secrets.CODECOV_TOKEN }} # required
      - name: Publish Unit Test Results
        uses: EnricoMi/publish-unit-test-result-action@v2
        if: always()
        with:
          files: "**/target/surefire-reports/*.xml"
      - uses: mmprogrami/after-maven-action@main




