---
name: build
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-latest, windows-latest, macos-latest ]
        java: [ 24 ]
        # also check (once) on latest
        include:
          - os: ubuntu-latest
            java: 8
    env:
      MAVEN_ARGS: '--no-transfer-progress'
      MAVEN_TARGET: 'package'
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: ${{ matrix.java }}
          distribution: 'temurin'
          cache: "maven"
          server-id: central
          server-username: CENTRAL_USERNAME
          server-password: CENTRAL_PASSWORD
          gpg-private-key: ${{ secrets.GPG_SECRET_KEY }}
      - name: Set Maven Target
        if: ${{ matrix.os == 'ubuntu-latest' && matrix.java == '8' }}
        run: echo "MAVEN_TARGET=deploy" >> $GITHUB_ENV
      - name: Build with Maven
        run: |
          mvn -B -Pdeploy  -D"maven.test.failure.ignore=true"  ${{ env.MAVEN_TARGET }}
        env:
          CENTRAL_USERNAME: ${{ secrets.CENTRAL_USERNAME }}
          CENTRAL_PASSWORD: ${{ secrets.CENTRAL_PASSWORD }}
          MAVEN_GPG_PASSPHRASE: ${{ secrets.GPG_SECRET_KEY_PASSPHRASE }}
      - uses: codecov/codecov-action@v4
        if: ${{ github.event_name == 'push'  && ! cancelled()  && matrix.os == 'ubuntu-latest' && matrix.java == '8' }}
        with:
          token: ${{ secrets.CODECOV_TOKEN }} # required
      - name: Publish Unit Test Results
        uses: EnricoMi/publish-unit-test-result-action@v2
        if: (success() || failure()) && runner.os == 'Linux'
        with:
          check_name: "Unit Test Results ${{ matrix.os }} / ${{ matrix.java }}"
          files: "**/target/surefire-reports/*.xml"
      - name: Publish Unit Test Results
        uses: EnricoMi/publish-unit-test-result-action/windows/bash@v2
        if: (success() || failure()) && runner.os == 'Windows'
        with:
          check_name: "Unit Test Results ${{ matrix.os }} / ${{ matrix.java }}"
          files: "**/target/surefire-reports/*.xml"
      - uses: MMProgrami/after-maven-action@1-dev
        if: true




